package mobile.contratodigital.dao;

import java.util.ArrayList;
import sharedlib.contratodigital.model.Cad_grupo_empres;

public class ListaComTodosGrupoEmpresa {

	public static ArrayList<Cad_grupo_empres> devolveLista() {

		ArrayList<Cad_grupo_empres> listaGrupoEmpresa = new ArrayList<Cad_grupo_empres>();
		
		listaGrupoEmpresa.add(new Cad_grupo_empres(1, "AGV LOGISTICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(2, "AIR LIQUIDE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(3, "ATLAS COPCO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(4, "CONSUMA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(5, "GRSA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(6, "GRAN SAPORE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(7, "GRECCO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(8, "HABIBS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(9, "MEGA CENTER SAINT GOBAIN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(10, "METROPOLITAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(11, "CBA - PURAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(12, "CHAMA SUPERMERCADOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(13, "FRANGO ASSADO RESTAURANTES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(14, "MOTEIS MAKAKUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(15, "QUALITY E QUALITY DO BRASIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(16, "RICOY SUPERMERCADOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(17, "ACADEMIAS RUNNER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(18, "BRASIL KIRIN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(19, "SODEXHO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(20, "MOTEIS TAJ MAHAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(21, "TAM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(22, "WALMART"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(23, "MARABRAZ"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(24, "PERALTA SUPERMERCADOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(25, "SUPERMERCADOS JOANIN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(26, "ONDINA ALIMENTACAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(27, "AGAPRINT"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(28, "COMERCIAL OSWALDO CRUZ"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(29, "DIAS PASTORINHO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(30, "MALTA E REZENDE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(31, "MEGAQUIMICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(32, "ACADEMIA ITALY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(33, "REFRIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(34, "MOTEIS IMPERIUM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(35, "SUPERMERCADOS CACULA DE BERTIOGA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(36, "CHURRASCARIA SOUTHS PLACE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(37, "TENDA ATACADO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(38, "LC ADM DE RESTAURANTES LTDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(39, "INBRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(40, "MOTEIS KAMISS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(41, "CHEIRO DE MATO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(42, "SINAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(43, "MASSA FINA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(44, "CHAVES GOLD"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(45, "HOTEL GAIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(46, "VALEO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(47, "MERCADINHO IPANEMA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(48, "LIG LIG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(49, "DIDIO PIZZA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(50, "VIRTUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(51, "LARGO DO GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(52, "CONSIGAZ COMERCIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(53, "PETROLIQ"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(54, "ITAIPAVA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(55, "ROLDAO ATACADISTA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(56, "PONTO FRIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(57, "VILLA ALLEGRO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(58, "SULTAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(59, "PAES E DOCES ASSEMBLEIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(60, "FLORENCE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(61, "ACADEMIA BIORITMO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(62, "FEIJAO DE CORDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(63, "AKKI ATACADISTA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(64, "REI DO ABADEJO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(65, "TYCO ELECTRONICS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(66, "ECOCHAPAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(67, "CLUBE ATLETICO MONTE LIBANO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(68, "GLOBALPACK"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(69, "CHURRASCARIA ESTANCIA C BELO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(70, "TECSIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(71, "BEF ALIMENTACAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(72, "MET MONTABIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(73, "BRAMA MATERIAIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(74, "ASTRA / JAPI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(75, "MERITOR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(76, "PARANOA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(77, "MRV CONSTRUTORA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(78, "PANIFICADORA GIARELLI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(79, "REDE RECORD"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(80, "BASF"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(81, "MIL GRAUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(82, "ALINUTRI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(83, "GONZALEZ MADEIREIRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(84, "MOTOR IN MOTEIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(85, "MOTEL CORSARIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(86, "VICTORIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(87, "LA VILLE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(88, "PILAO MINEIRO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(89, "LABORTEX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(90, "KANAFLEX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(91, "PRECI CASTING MEGA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(92, "PADARIAS PASTOR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(93, "GRILLARICA RESTAURANTES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(94, "CHANGRILA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(95, "VIBELMETAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(96, "ESPORTE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(97, "PRAIAMAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(98, "MPRATO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(99, "BEM SANTA INES / MARILIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(100, "COLGATE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(101, "BORBA GATO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(102, "POLIMIX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(103, "EDITORA MODERNA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(104, "METALFRIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(105, "BENTOMAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(106, "PIRELLI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(107, "INTEGRACAO BRASIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(108, "WORK CHEESE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(109, "EBF VAZ"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(110, "LINCOLN ELETRIC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(111, "MASAKI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(112, "OUTBACK"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(113, "VIP ACADEMIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(114, "VULCABRAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(115, "WAP METAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(116, "BASSO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(117, "AMORIM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(118, "HIGAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(119, "ILHAMAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(120, "BALANCIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(121, "BRASALPLA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(122, "REDECAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(123, "DIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(124, "PROTEGE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(125, "UNIAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(126, "ASSOC ALIANCA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(127, "JORSIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(128, "KSB"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(129, "MOTEL B VIANA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(130, "CONSTRUDECOR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(131, "M CASSAB"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(132, "METAX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(133, "MAR CLARO SUSHI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(134, "WALLTEC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(135, "SILUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(136, "JOLITEX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(137, "RR DONNELLEY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(138, "SPA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(139, "BANCOBRASIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(140, "LOURENCINI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(141, "RTL HOTELARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(142, "SUN CHEMICAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(143, "HOMEPLAY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(144, "BK BRASIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(145, "BELFORT"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(146, "IRMAOS BRITO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(147, "AGULHAS NEGRAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(148, "SETA ATACADISTA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(149, "ARTEB"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(150, "ARTHUR BIANCHINI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(151, "HERINGER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(152, "MESSASTAMP"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(153, "RANCHO MINEIRO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(154, "NAKATO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(155, "BRASILMAXI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(156, "SUPERM. NAGUMO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(157, "GRUPO IRIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(158, "RODONAVES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(159, "VILLAS CHURRASCARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(160, "GRAN PALATO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(161, "MERCEARIA RENATA / MTX GEN COM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(162, "LOIOLA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(163, "PARK GAS (KALIL)"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(164, "NICHIBRAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(165, "MARY LUCI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(166, "FAMA/FAB"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(167, "FENIX MOTEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(168, "PROTURBO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(169, "ED. ATICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(170, "TW ESPUMA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(171, "TEGMA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(172, "COATEX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(173, "POLY VAC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(174, "MERCEDES BENZ"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(175, "SERVENG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(176, "NOVA LATA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(177, "PIZZA HUT"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(178, "COMEP"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(179, "DE NIGRIS MOTORS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(180, "FORT GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(181, "TEREZINHA GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(182, "JUREMA GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(183, "ILARIO GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(184, "BOTELHO GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(185, "SALOMAO GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(186, "PRACA GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(187, "GASBOM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(188, "SUPERVAREJAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(189, "RUIZ"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(190, "DINHO GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(191, "CDA COM."));
		listaGrupoEmpresa.add(new Cad_grupo_empres(192, "REPUXACAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(193, "ROMI S A"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(194, "HYPERMARCAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(195, "AVES ABATIDAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(196, "GRUPO NS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(197, "TAMBORE S A"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(198, "BILL GRILL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(199, "NACCO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(200, "SONDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(201, "ITORORO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(202, "DBSB REF"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(203, "AYUMI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(204, "HORTIFRUTI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(205, "ZTEC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(206, "BOM PARTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(207, "ESBELT LINGERIE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(208, "IBRATEC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(209, "NUTSTEELL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(210, "5M COM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(211, "TFL FERRAMENTARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(212, "RENOME REFEICOES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(213, "TIDE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(214, "MOTEL 2000"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(215, "KROCODILO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(216, "PURATOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(217, "MULTIGRADE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(218, "KANDAHALI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(219, "GASMAIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(220, "OKINAWA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(221, "AGR EXTRUSAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(222, "POSTO PROGRESSO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(223, "ATLANTIDA MG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(224, "SUSHI BAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(225, "PANTER HOTEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(226, "HGD"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(227, "CAVIGLIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(228, "TRANS AMERICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(229, "BALALAIKA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(230, "DANIELLE & JEISON"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(231, "C & E"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(232, "BRUNO FREIRE ROSEMBERG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(233, "VANDERLEI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(234, "RISA RESTAURANTE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(235, "DASMENINAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(236, "HUFFIX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(237, "MAZAFERRO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(238, "PEDREIRA STA ISABEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(239, "APARAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(240, "METALIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(241, "BRASILEIRAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(242, "CONTINENTAL PNEUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(243, "VITARA MOTEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(244, "MONTMAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(245, "FRANGAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(246, "USINA FORTALEZA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(247, "CIA DO PALLET"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(248, "JELLY FISH"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(249, "ULTRABASES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(250, "AHLSTROM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(251, "ROCKFIBRAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(252, "PANIF ALVARENGA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(253, "SRODRIGUES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(254, "GRANEIRO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(255, "LAP CHURRASCARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(256, "BRUCAI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(257, "MARCELO BALDONI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(258, "CARBOTEX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(259, "FURQUIM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(261, "FAMA GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(262, "AGUA NA BOCA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(263, "PANCO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(264, "ALPINO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(265, "BARTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(266, "NUTRIPLUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(267, "ANFOLABOR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(268, "TONNEY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(269, "ATLAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(270, "CONDOMINIOS ODAIR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(271, "PINHANLENSE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(272, "BOI GAUCHO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(273, "DANELON"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(274, "RODOSNACK"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(275, "SUPERMERCADOS SAVEGNAGO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(276, "PRIMOS SUPERMERCADOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(277, "LINDAURA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(279, "OSAKA/YOSUGIRO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(280, "AUXILIADORA PREDIAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(281, "TEMP MASTER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(282, "SUPERMERCADO X"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(283, "VEUSUVIUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(284, "MAURO PISOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(285, "ANDRADE BRITTA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(286, "L ENERGIE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(287, "VILLE GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(288, "ATIVA ALIM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(289, "PINTURAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(290, "GRUPO PAO DE ACUCAR (CBD)"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(291, "ATIVA ALIM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(292, "LEAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(293, "DICICO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(294, "VALE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(295, "WILDEBLOC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(296, "QUALICOR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(297, "SAN SUPERMERCADOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(298, "PRODUQUIMICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(299, "OBJETIVA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(300, "GUARIDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(301, "ANOTHER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(302, "ARIANE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(303, "SANTA CLARA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(304, "PAGOTI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(305, "MIKAMI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(306, "COMERCIAL GARCIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(307, "AG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(308, "PENA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(309, "RIZZO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(310, "RONIFARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(311, "SALAMON"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(312, "COMERCIO PARANA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(313, "MANFREDINI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(314, "MAPRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(315, "NETO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(316, "DISTRIBUIDORA DE CIMENTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(317, "INDUSTRIA TEXTIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(318, "INDUSTRIA MCA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(319, "COVOLAN INDUSTRIA TEXTIL LTDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(320, "TOLEDO GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(321, "NOVA GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(322, "GAVA GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(323, "FENIKSO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(324, "TRES UNIAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(325, "IRAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(326, "HASSAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(327, "ISAIAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(328, "GERSON"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(329, "VANDERLEI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(330, "ARMANDO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(331, "BAIXINHO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(332, "MOREIRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(333, "FLORESTA SUPERMERCADOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(334, "HISPEX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(335, "VALE VERDE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(336, "BARRA MANSA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(337, "HOTEIS CARBALLO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(338, "MANOLO VITARA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(339, "GORDON"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(340, "VALDIR MAMEDIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(341, "DELUMA I"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(342, "DELUMA II"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(343, "DELPHI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(344, "NUCLEO CORACAO MATERNO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(345, "RODHIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(346, "ECOLAB"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(347, "PIETRAS MOTEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(348, "MUNDIAL E LAMASSAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(349, "RESTAURANTE PETRUCIO S"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(350, "TRANSCOB"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(351, "ACCOR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(352, "PORTAS DO SOL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(353, "QUALITA REFEICOES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(354, "LL PIZZARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(355, "DELLA PANIFICADORA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(356, "GOURMET RESTAURANTE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(357, "PANIFICADORA ESQUINA DO PAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(358, "CESLOG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(359, "GAIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(360, "RESTAURANTE 1º OPCAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(361, "ALIANCA SERVICOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(362, "BATALHA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(363, "WICKBOLD"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(364, "CAMELODROMO DE CAMPINAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(365, "PAGUE MENOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(366, "GRACE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(367, "TERRACOM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(368, "SCHULTZ GRILL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(369, "MET GUAPORE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(370, "B A BARBOSA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(371, "CHARLEVILLE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(372, "SUPERMERCADO CANOSSA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(373, "PARQUE DOS EUCALIPITOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(374, "LUMA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(375, "ASTEN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(376, "SIMOSO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(377, "ANGOLINI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(378, "TRANSPORTES COVRE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(379, "EAT"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(380, "PEDREIRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(381, "BELCAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(382, "INTERNATIONAL PAPER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(383, "CERVITELHAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(384, "TRANSCOBER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(385, "JULIO SIMOES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(386, "MACOM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(387, "ECOFABRIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(388, "COME COME LANCHONETE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(389, "VALLI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(390, "BRUNHOLI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(391, "GOLDPAC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(392, "MARELLA S"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(393, "PLAYBALL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(394, "REDE DA CONSTRUCAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(395, "SUPEREURO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(396, "SUPEREURO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(397, "ESTANCIA GRILL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(398, "RIO VERMELHO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(399, "JANGADA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(400, "CROMUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(401, "SHIBATA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(402, "SUMARE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(403, "AUXILIADORA PREDIAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(404, "OBJETIVA CONDOMINIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(405, "GUARIDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(406, "EMPORIO BOTEGA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(407, "TORRE GRILL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(408, "DISTRIBUIDORA IMPARCIAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(409, "SUPERSETE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(410, "DREGER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(411, "ADENILSON FERREIRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(412, "AUXILIADORA PREDIAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(413, "SINDEEPRES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(414, "GUARIDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(415, "ESPORTE CACHOEIRNHA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(416, "CAIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(417, "AUTOMOTIVA SA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(418, "JS ARAUJO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(419, "DEHEUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(420, "PRAIANA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(421, "RAMUTH"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(422, "COMENDADOR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(423, "JERIVA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(424, "GIANINI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(425, "SALEH"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(426, "DIVINUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(427, "PEDRO & PEDROS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(428, "ISOTRAFO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(429, "EMPORIO BETHAVILLE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(430, "MARCONATO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(431, "CENTRAL MINERIOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(432, "ADM AUTO NIVEL CONDOMINIOS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(433, "OROCATTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(434, "KINGCHURRAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(435, "GRENALSIMONETTI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(436, "NUTRIBEM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(437, "VILLE HOUSE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(438, "COZINHA NATIVA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(439, "BON NETTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(440, "HEINZ BRASIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(441, "BAURUPAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(442, "BRASILUSA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(443, "CONDOMINIO GREEN VALLEY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(444, "PEDRA BAIANA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(445, "VILA DOS DOCES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(446, "FAIRBANKS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(447, "CANAA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(448, "VITTA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(449, "BERTUZZI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(450, "FITOSSANITY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(451, "GHISOLFI LOG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(452, "RAIZEN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(453, "GILMAR GAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(454, "GRAN AMORE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(455, "AL E OS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(456, "RONALDO REST"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(457, "DOCK MACK"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(458, "BEDUINO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(459, "FONTES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(460, "BUON GUSTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(461, "REDE LITORAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(462, "DULIGAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(463, "LAVILLE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(464, "ATLANTICA HOTEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(465, "MAC ATACADO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(466, "DAOLIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(467, "SANOLI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(468, "PANIFICADORA MOREIRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(469, "ASSADOS E CIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(470, "REDE BEM PRATICO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(471, "RPERTILE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(472, "INSTITUITO DOM DECIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(473, "ADMINISTRADORA VILA RICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(474, "ADMINISTRADORA FERNANDO TROFF"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(475, "JUNIOR RESTAURANTE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(476, "GIFEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(477, "MULTIPLUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(478, "PERBONI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(479, "EXCLUSIVA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(480, "CEREJEIRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(481, "ALTA CITY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(482, "ACQUACENTER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(483, "FONTE LEONE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(484, "UNDER DOG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(485, "REDE HORTIFRUTI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(486, "MAXIMO SUP"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(487, "PEZZI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(488, "VILA RICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(489, "GREEN VALLEY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(490, "CHINAINBOX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(491, "VIVA FOOD"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(492, "MARANGON"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(493, "SMART"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(494, "SUPERMERCADO RIMAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(495, "IMERYS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(496, "CONSULADO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(497, "MULTIMAGLOG"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(498, "CAZELA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(499, "POLARFIX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(500, "SPERINDE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(501, "OVER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(502, "VERALLIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(503, "VILLA ROSSA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(504, "TOSCHA ARABIAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(505, "SABOR DE GOIAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(506, "TURIM RESTAURANTE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(507, "BAHREM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(508, "BOA MORADA MAT DE CONSTRUÇÃO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(509, "ANDRE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(510, "SUPERMERCADO TEND TUDO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(511, "ZCT&BLR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(512, "TRANSPADUA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(513, "YELLOW MOTEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(514, "TEND TUDO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(515, "VEGANO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(516, "PROPRIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(517, "CONFIANÇA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(518, "SPANI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(519, "FRA MULLER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(520, "FISH FERTIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(521, "CANDEEIROS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(522, "STARMINAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(523, "AMIC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(524, "OPETRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(525, "POLY EASY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(526, "NG METALURGICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(527, "PRATIKO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(528, "MARCO AURELIO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(529, "IBIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(530, "GUARIDA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(531, "MRV"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(532, "PRYSMIAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(533, "JVA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(534, "ZERO 62"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(535, "I&M PAPEIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(536, "MOINHO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(537, "NUOVA ACADEMIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(538, "DOCE PALADAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(539, "VOGUE ALIMENTACAO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(540, "BRUNETTI POUSADA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(541, "BOTECO POSTO 15"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(542, "PROVIDER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(543, "MONREALE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(544, "BOVINUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(545, "FREIRE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(546, "TPLAN"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(547, "BOI NA BRASA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(548, "MONTECARLO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(549, "FRUTIMIX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(550, "AC CHURRASCARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(552, "SUPERMERCADO ASP"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(553, "AMIC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(554, "BAMBUZAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(555, "MULTIGALVA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(556, "MELHOR ALIMENTAÇÃO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(557, "PERFAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(559, "COMERCIAL ZARAGOZA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(560, "COMIL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(561, "PEPE GRILL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(562, "MARRUCCI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(563, "ETIKA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(564, "GNANNI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(565, "SUMMER"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(566, "PIC NIC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(567, "CASA DO SINDICO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(568, "PROVERAÇO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(569, "MONREALE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(570, "CELIO MELILO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(571, "HIDROAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(572, "AVIBRAS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(573, "DELLA VIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(574, "VERALLIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(575, "CREDOTO REAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(576, "COND VERSAILLES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(577, "PIZZARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(578, "FRANDELICIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(579, "O MATUTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(580, "SUPER SHOW"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(581, "BOOM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(582, "WGARCIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(583, "HOTELEIROS MOTEIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(584, "RESTFLOVINC"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(585, "SAVEGNAGO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(586, "STRAND HOTEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(587, "MINT"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(588, "DELTA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(589, "ANGAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(590, "ELDORADO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(591, "SLICE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(592, "EVONIK DEGUSA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(593, "MULTIBRINK"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(594, "CREDITO REAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(595, "PRONUTRI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(596, "FISIO ACADEMIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(597, "MADRI PAES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(598, "COPEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(599, "TAUBATES"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(600, "PIZZA Z"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(601, "RIAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(602, "SAPORE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(603, "SODEXO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(604, "ALIMENTARE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(605, "CURY"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(607, "BELENUS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(608, "SALTORELLI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(609, "DON PATTO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(610, "PLASDONI"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(611, "DEPOTRAM"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(612, "COVABRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(613, "ETECE ADMINISTRADORA DE IMOVEIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(614, "ANDRETA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(620, "GRAMADO ADMINISTRADORA DE IMOVEIS"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(637, "SP IMOBILIARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(638, "LITORAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(639, "RESTAURANTE MOURÃO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(640, "RACHID"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(641, "AMBIANCE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(642, "ADM TROTT"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(643, "MAGNIFICA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(644, "O ESPETÃO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(645, "DIVINUS FOOD"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(646, "CORTESIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(647, "SUPERLISBOA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(648, "BAXIMBAR"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(649, "ALTO NIVEL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(650, "A3 IMOBILIARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(651, "SUPERMERCADO TRINDADE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(652, "PANIFICADORALIGIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(653, "PLAXTEX"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(654, "BOA SORTE RESTAURANTE"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(655, "BORGES LANDEIRO"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(656, "TONI PIZZARIA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(657, "MAFRA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(658, "CIMENTHUBA"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(659, "RIAL"));
		listaGrupoEmpresa.add(new Cad_grupo_empres(660, "ALIANÇA"));
		
		return listaGrupoEmpresa;
	}
	
	
	
}
