package mobile.contratodigital.dao;

import java.util.ArrayList;

import sharedlib.contratodigital.model.Cad_atividade;

public class ListaComTodasAtividadesEconomica {

	/*
	public static ArrayList<Cad_atividade> devolveLista() {

		ArrayList<Cad_atividade> listaAtividadeEconomica = new ArrayList<Cad_atividade>();
		
		listaAtividadeEconomica.add(new Cad_atividade("1113", "CULTIVO DE CEREAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("1121", "CULTIVO DE ALGODAO HERBACEO E DE OUTRAS"));
		listaAtividadeEconomica.add(new Cad_atividade("1130", "CULTIVO DE CANA DE ACUCAR"));
		listaAtividadeEconomica.add(new Cad_atividade("1148", "CULTIVO DE FUMO"));
		listaAtividadeEconomica.add(new Cad_atividade("1156", "CULTIVO DE SOJA"));
		listaAtividadeEconomica.add(new Cad_atividade("1164", "CULTIVO DE OLEAGINOSAS DE LAVOURA TEMPOR"));
		listaAtividadeEconomica.add(new Cad_atividade("1199", "CULTIVO DE PLANTAS DE LAVOURA TEMPORARIA"));
		listaAtividadeEconomica.add(new Cad_atividade("1211", "HORTICULTURA"));
		listaAtividadeEconomica.add(new Cad_atividade("1229", "CULTIVO DE FLORES E PLANTAS ORNAMENTAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("1318", "CULTIVO DE LARANJA"));
		listaAtividadeEconomica.add(new Cad_atividade("1326", "CULTIVO DE UVA"));
		listaAtividadeEconomica.add(new Cad_atividade("1342", "CULTIVO DE CAFE"));
		listaAtividadeEconomica.add(new Cad_atividade("1351", "CULTIVO DE CACAU"));
		listaAtividadeEconomica.add(new Cad_atividade("1393", "CULTIVO DE PLANTAS DE LAVOURA PERMANENTE"));
		listaAtividadeEconomica.add(new Cad_atividade("1415", "PRODUÇAO DE SEMENTES CERTIFICADAS"));
		listaAtividadeEconomica.add(new Cad_atividade("1423", "PRODUÇAO DE MUDAS E OUTRAS FORMAS DE PRO"));
		listaAtividadeEconomica.add(new Cad_atividade("1512", "CRIAÇAO DE BOVINOS"));
		listaAtividadeEconomica.add(new Cad_atividade("1539", "CRIAÇAO DE CAPRINOS E OVINOS"));
		listaAtividadeEconomica.add(new Cad_atividade("1547", "CRIAÇÃO DE SUINOS"));
		listaAtividadeEconomica.add(new Cad_atividade("1555", "CRIAÇÃO DE AVES"));
		listaAtividadeEconomica.add(new Cad_atividade("1598", "CRIACAO DE ANIMAIS NAO ESPECIFICADOS ANT"));
		listaAtividadeEconomica.add(new Cad_atividade("1610", "ATIVIDADES DE APOIO A AGRICULTURA"));
		listaAtividadeEconomica.add(new Cad_atividade("1628", "ATIVIDADES DE APOIO À PECUÁRIA"));
		listaAtividadeEconomica.add(new Cad_atividade("1636", "ATIVIDADES DE POS COLHEITA"));
		listaAtividadeEconomica.add(new Cad_atividade("1709", "CACA E SERVIÇOS RELACIONADOS"));
		listaAtividadeEconomica.add(new Cad_atividade("2101", "PRODUÇÃO FLORESTAL - FLORESTAS PLANTADAS"));
		listaAtividadeEconomica.add(new Cad_atividade("2209", "PRODUÇÃO FLORESTAL - FLORESTAS NATIVAS"));
		listaAtividadeEconomica.add(new Cad_atividade("2306", "ATIVIDADES DE APOIO A PRODUÇÃO FLORESTAL"));
		listaAtividadeEconomica.add(new Cad_atividade("3116", "PESCA EM AGUA SALGADA"));
		listaAtividadeEconomica.add(new Cad_atividade("3124", "PESCA EM ÁGUA DOCE"));
		listaAtividadeEconomica.add(new Cad_atividade("3213", "AQÜICULTURA EM ÁGUA SALGADA E SALOBRA"));
		listaAtividadeEconomica.add(new Cad_atividade("3221", "AQUICULTURA EM ÁGUA DOCE"));
		listaAtividadeEconomica.add(new Cad_atividade("5003", "EXTRAÇÃO DE CARVÃO MINERAL"));
		listaAtividadeEconomica.add(new Cad_atividade("6000", "EXTRAÇÃO DE PETRÓLEO E GÁS NATURAL"));
		listaAtividadeEconomica.add(new Cad_atividade("7103", "EXTRAÇÃO DE MINÉRIO DE FERRO"));
		listaAtividadeEconomica.add(new Cad_atividade("7219", "EXTRAÇÃO DE MINÉRIO DE ALUMÍNIO"));
		listaAtividadeEconomica.add(new Cad_atividade("7227", "EXTRAÇÃO DE MINÉRIO DE ESTANHO"));
		listaAtividadeEconomica.add(new Cad_atividade("7235", "EXTRAÇÃO DE MINÉRIO DE MANGANES"));
		listaAtividadeEconomica.add(new Cad_atividade("7243", "EXTRAÇÃO DE MINÉRIO DE METAIS PRECIOSOS"));
		listaAtividadeEconomica.add(new Cad_atividade("7251", "EXTRAÇÃO DE MINERAIS RADIOATIVOS"));
		listaAtividadeEconomica.add(new Cad_atividade("8100", "EXTRACAO DE PEDRA, AREIA E ARGILA"));
		listaAtividadeEconomica.add(new Cad_atividade("8916", "EXTRAÇÃO DE MINERAIS PARA FABRICAÇÃO DE"));
		listaAtividadeEconomica.add(new Cad_atividade("8932", "EXTRAÇÃO DE GEMAS PEDRAS PRECIOSAS E SE"));
		listaAtividadeEconomica.add(new Cad_atividade("9106", "ATIVIDADES DE APOIO A EXTRAÇÃO DE PETRÓL"));
		listaAtividadeEconomica.add(new Cad_atividade("10112", "ABATE DE RESES, EXCETO SUÍNOS"));
		listaAtividadeEconomica.add(new Cad_atividade("10139", "FABRICAÇÃO DE PRODUTOS DE CARNE"));
		listaAtividadeEconomica.add(new Cad_atividade("10201", "PRESERVAÇÃO DO PESCADO E FABRICAÇÃO DE P"));
		listaAtividadeEconomica.add(new Cad_atividade("10317", "FABRICAÇÃO DE CONSERVAS DE FRUTAS"));
		listaAtividadeEconomica.add(new Cad_atividade("10333", "FABRICAÇÃO DE CONSERVAS DE LEGUMES E OUT"));
		listaAtividadeEconomica.add(new Cad_atividade("10511", "PREPARACAO DO LEITE"));
		listaAtividadeEconomica.add(new Cad_atividade("10520", "FABRICAÇÃO DE LATICÍNIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("10619", "BENEFICIAMENTO DE ARROZ E FABRICAÇÃO DE"));
		listaAtividadeEconomica.add(new Cad_atividade("10635", "FABRICAÇÃO DE FARINHA DE MANDIOCA E DERI"));
		listaAtividadeEconomica.add(new Cad_atividade("10643", "FABRICAÇÃO DE FARINHA DE MILHO E DERIVAD"));
		listaAtividadeEconomica.add(new Cad_atividade("10660", "FABRICAÇÃO DE ALIMENTOS PARA ANIMAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("10716", "FABRICAÇÃO DE AÇÚCAR EM BRUTO"));
		listaAtividadeEconomica.add(new Cad_atividade("10724", "FABRICAÇÃO DE AÇÚCAR REFINADO"));
		listaAtividadeEconomica.add(new Cad_atividade("10813", "TORREFAÇÃO E MOAGEM DE CAFÉ"));
		listaAtividadeEconomica.add(new Cad_atividade("10821", "FABRICAÇÃO DE PRODUTOS À BASE DE CAFÉ"));
		listaAtividadeEconomica.add(new Cad_atividade("10911", "FABRICACAO DE PRODUTOS DE PANIFICACAO"));
		listaAtividadeEconomica.add(new Cad_atividade("10929", "FABRICACAO DE BISCOITOS E BOLACHAS"));
		listaAtividadeEconomica.add(new Cad_atividade("10945", "FABRICACAO DE MASSAS ALIMENTÍCIAS"));
		listaAtividadeEconomica.add(new Cad_atividade("10953", "FABRICAÇÃO DE ESPECIARIAS, MOLHOS, TEMPE"));
		listaAtividadeEconomica.add(new Cad_atividade("10961", "FABRICAÇÃO DE ALIMENTOS E PRATOS PRONTOS"));
		listaAtividadeEconomica.add(new Cad_atividade("11127", "FABRICACAO DE VINHO"));
		listaAtividadeEconomica.add(new Cad_atividade("11135", "FABRICACAO DE MALTE, CERVEJAS E CHOPES"));
		listaAtividadeEconomica.add(new Cad_atividade("11216", "FABRICACAO DE AGUAS ENVASADAS"));
		listaAtividadeEconomica.add(new Cad_atividade("12107", "PROCESSAMENTO INDUSTRIAL DO FUMO"));
		listaAtividadeEconomica.add(new Cad_atividade("12204", "FABRICAÇÃO DE PRODUTOS DO FUMO"));
		listaAtividadeEconomica.add(new Cad_atividade("13111", "PREPARACAO E FIACAO DE FIBRAS DE ALGODAO"));
		listaAtividadeEconomica.add(new Cad_atividade("13219", "TECELAGEM DE FIOS DE ALGODÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("13308", "FABRICAÇÃO DE TECIDOS DE MALHA"));
		listaAtividadeEconomica.add(new Cad_atividade("13529", "FABRICACAO DE ARTEFATOS DE TAPECARIA"));
		listaAtividadeEconomica.add(new Cad_atividade("13537", "FABRICACAO DE ARTEFATOS DE CORDOARIA"));
		listaAtividadeEconomica.add(new Cad_atividade("14118", "CONFECCAO DE ROUPAS INTIMAS"));
		listaAtividadeEconomica.add(new Cad_atividade("14134", "CONFECÇÃO DE ROUPAS PROFISSIONAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("14215", "FABRICACAO DE MEIAS"));
		listaAtividadeEconomica.add(new Cad_atividade("15106", "CURTIMENTO E OUTRAS PREPARAÇÕES DE COURO"));
		listaAtividadeEconomica.add(new Cad_atividade("15297", "FABRICAÇÃO DE ARTEFATOS DE COURO NÃO ESP"));
		listaAtividadeEconomica.add(new Cad_atividade("15319", "FABRICACAO DE CALCADOS DE COURO"));
		listaAtividadeEconomica.add(new Cad_atividade("15327", "FABRICAÇÃO DE TÊNIS DE QUALQUER MATERIAL"));
		listaAtividadeEconomica.add(new Cad_atividade("15335", "FABRICAÇÃO DE CALÇADOS DE MATERIAL SINTÉ"));
		listaAtividadeEconomica.add(new Cad_atividade("16102", "DESDOBRAMENTO DE MADEIRA"));
		listaAtividadeEconomica.add(new Cad_atividade("17214", "FABRICACAO DE PAPEL"));
		listaAtividadeEconomica.add(new Cad_atividade("17222", "FABRICAÇÃO DE CARTOLINA E PAPELCARTÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("17311", "FABRICACAO DE EMBALAGENS DE PAPEL"));
		listaAtividadeEconomica.add(new Cad_atividade("17320", "FABRICAÇÃO DE EMBALAGENS DE CARTOLINA E"));
		listaAtividadeEconomica.add(new Cad_atividade("18121", "IMPRESSÃO DE MATERIAL DE SEGURANÇA"));
		listaAtividadeEconomica.add(new Cad_atividade("18130", "IMPRESSÃO DE MATERIAIS PARA OUTROS USOS"));
		listaAtividadeEconomica.add(new Cad_atividade("18211", "SERVIÇOS DE PRÉ-IMPRESSÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("18229", "SERVIÇOS DE ACABAMENTOS GRÁFICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("18300", "REPRODUÇÃO DE MATERIAIS GRAVADOS EM QUAL"));
		listaAtividadeEconomica.add(new Cad_atividade("19101", "COQUERIAS"));
		listaAtividadeEconomica.add(new Cad_atividade("19225", "FABRICAÇÃO DE PRODUTOS DERIVADOS DO PETR"));
		listaAtividadeEconomica.add(new Cad_atividade("19314", "FABRICAÇÃO DE ÁLCOOL"));
		listaAtividadeEconomica.add(new Cad_atividade("19322", "FABRICAÇÃO DE BIOCOMBUSTÍVEIS, EXCETO ÁL"));
		listaAtividadeEconomica.add(new Cad_atividade("20118", "FABRICAÇÃO DE CLORO E ÁLCALIS"));
		listaAtividadeEconomica.add(new Cad_atividade("20134", "FABRICACAO DE ADUBOS E FERTILIZANTES"));
		listaAtividadeEconomica.add(new Cad_atividade("20142", "FABRICACAO DE GASES INDUSTRIAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("20312", "FABRICAÇÃO DE RESINAS TERMOPLÁSTICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("20321", "FABRICAÇÃO DE RESINAS TERMOFIXAS"));
		listaAtividadeEconomica.add(new Cad_atividade("20339", "FABRICAÇÃO DE ELASTÔMEROS"));
		listaAtividadeEconomica.add(new Cad_atividade("20517", "FABRICAÇÃO DE DEFENSIVOS AGRÍCOLAS"));
		listaAtividadeEconomica.add(new Cad_atividade("20525", "FABRICAÇÃO DE DESINFESTANTES DOMISSANITÁ"));
		listaAtividadeEconomica.add(new Cad_atividade("20720", "FABRICAÇÃO DE TINTAS DE IMPRESSÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("20738", "FABRICAÇÃO DE IMPERMEABILIZANTES, SOLVEN"));
		listaAtividadeEconomica.add(new Cad_atividade("20916", "FABRICAÇÃO DE ADESIVOS E SELANTES"));
		listaAtividadeEconomica.add(new Cad_atividade("20924", "FABRICAÇÃO DE EXPLOSIVOS"));
		listaAtividadeEconomica.add(new Cad_atividade("20932", "FABRICAÇÃO DE ADITIVOS DE USO INDUSTRIAL"));
		listaAtividadeEconomica.add(new Cad_atividade("20941", "FABRICAÇÃO DE CATALISADORES"));
		listaAtividadeEconomica.add(new Cad_atividade("21106", "FABRICAÇÃO DE PRODUTOS FARMOQUÍMICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("21220", "FABRICAÇÃO DE MEDICAMENTOS PARA USO VETE"));
		listaAtividadeEconomica.add(new Cad_atividade("21238", "FABRICAÇÃO DE PREPARAÇÕES FARMACÊUTICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("22111", "FABRICAÇÃO DE PNEUMÁTICOS E DE CÂMARAS-D"));
		listaAtividadeEconomica.add(new Cad_atividade("22129", "REFORMA DE PNEUMÁTICOS USADOS"));
		listaAtividadeEconomica.add(new Cad_atividade("22234", "FABRICAÇÃO DE TUBOS E ACESSÓRIOS DE MATE"));
		listaAtividadeEconomica.add(new Cad_atividade("23117", "FABRICAÇÃO DE VIDRO PLANO E DE SEGURANÇA"));
		listaAtividadeEconomica.add(new Cad_atividade("23192", "FABRICAÇÃO DE ARTIGOS DE VIDRO"));
		listaAtividadeEconomica.add(new Cad_atividade("23206", "FABRICAÇÃO DE CIMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("23427", "FABRICAÇÃO DE PRODUTOS CERÂMICOS NÃO-REF"));
		listaAtividadeEconomica.add(new Cad_atividade("23923", "FABRICAÇÃO DE CAL E GESSO"));
		listaAtividadeEconomica.add(new Cad_atividade("24113", "PRODUÇÃO DE FERROGUSA"));
		listaAtividadeEconomica.add(new Cad_atividade("24121", "PRODUÇÃO DE FERROLIGAS"));
		listaAtividadeEconomica.add(new Cad_atividade("24211", "PRODUÇÃO DE SEMI-ACABADOS DE AÇO"));
		listaAtividadeEconomica.add(new Cad_atividade("24229", "PRODUÇÃO DE LAMINADOS PLANOS DE AÇO"));
		listaAtividadeEconomica.add(new Cad_atividade("24237", "PRODUÇÃO DE LAMINADOS LONGOS DE AÇO"));
		listaAtividadeEconomica.add(new Cad_atividade("24318", "PRODUÇÃO DE TUBOS DE AÇO COM COSTURA"));
		listaAtividadeEconomica.add(new Cad_atividade("24393", "PRODUÇÃO DE OUTROS TUBOS DE FERRO E AÇO"));
		listaAtividadeEconomica.add(new Cad_atividade("24415", "METALURGIA DO ALUMÍNIO E SUAS LIGAS"));
		listaAtividadeEconomica.add(new Cad_atividade("24423", "METALURGIA DOS METAIS PRECIOSOS"));
		listaAtividadeEconomica.add(new Cad_atividade("24431", "METALURGIA DO COBRE"));
		listaAtividadeEconomica.add(new Cad_atividade("24512", "FUNDIÇÃO DE FERRO E AÇO"));
		listaAtividadeEconomica.add(new Cad_atividade("25110", "FABRICAÇÃO DE ESTRUTURAS METÁLICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("25128", "FABRICAÇÃO DE ESQUADRIAS DE METAL"));
		listaAtividadeEconomica.add(new Cad_atividade("25411", "FABRICAÇÃO DE ARTIGOS DE CUTELARIA"));
		listaAtividadeEconomica.add(new Cad_atividade("25438", "FABRICAÇÃO DE FERRAMENTAS"));
		listaAtividadeEconomica.add(new Cad_atividade("25501", "FABRICAÇÃO DE EQUIPAMENTO BÉLICO PESADO"));
		listaAtividadeEconomica.add(new Cad_atividade("25918", "FABRICAÇÃO DE EMBALAGENS METÁLICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("26108", "FABRICAÇÃO DE COMPONENTES ELETRÔNICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("26221", "FABRICAÇÃO DE PERIFÉRICOS PARA EQUIPAMEN"));
		listaAtividadeEconomica.add(new Cad_atividade("26311", "FABRICAÇÃO DE EQUIPAMENTOS TRANSMISSORES"));
		listaAtividadeEconomica.add(new Cad_atividade("26329", "FABRICAÇÃO DE APARELHOS TELEFÔNICOS E DE"));
		listaAtividadeEconomica.add(new Cad_atividade("26400", "FABRICAÞÒO DE PRODUTOS CERÔMICOS "));
		listaAtividadeEconomica.add(new Cad_atividade("26515", "FABRICAÇÃO DE APARELHOS E EQUIPAMENTOS D"));
		listaAtividadeEconomica.add(new Cad_atividade("26523", "FABRICAÇÃO DE CRONÔMETROS E RELÓGIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("26604", "FABRICAÇÃO DE APARELHOS ELETROMÉDICOS E"));
		listaAtividadeEconomica.add(new Cad_atividade("26809", "FABRICAÇÃO DE MÍDIAS VIRGENS, MAGNÉTICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("27228", "FABRICAÇÃO DE BATERIAS E ACUMULADORES PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28119", "FABRICAÇÃO DE MOTORES E TURBINAS, EXCETO"));
		listaAtividadeEconomica.add(new Cad_atividade("28143", "FABRICAÇÃO DE COMPRESSORES"));
		listaAtividadeEconomica.add(new Cad_atividade("28216", "FABRICAÇÃO DE APARELHOS E EQUIPAMENTOS P"));
		listaAtividadeEconomica.add(new Cad_atividade("28241", "FABRICAÇÃO DE APARELHOS E EQUIPAMENTOS D"));
		listaAtividadeEconomica.add(new Cad_atividade("28259", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28291", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS DE"));
		listaAtividadeEconomica.add(new Cad_atividade("28313", "FABRICAÇÃO DE TRATORES AGRÍCOLAS"));
		listaAtividadeEconomica.add(new Cad_atividade("28321", "FABRICAÇÃO DE EQUIPAMENTOS PARA IRRIGAÇÃ"));
		listaAtividadeEconomica.add(new Cad_atividade("28402", "FABRICAÇÃO DE MÁQUINASFERRAMENTA"));
		listaAtividadeEconomica.add(new Cad_atividade("28518", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28534", "FABRICAÇÃO DE TRATORES, EXCETO AGRÍCOLAS"));
		listaAtividadeEconomica.add(new Cad_atividade("28542", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28623", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28631", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28640", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28658", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("28666", "FABRICAÇÃO DE MÁQUINAS E EQUIPAMENTOS PA"));
		listaAtividadeEconomica.add(new Cad_atividade("29204", "FABRICAÇÃO DE CAMINHÕES E ÔNIBUS"));
		listaAtividadeEconomica.add(new Cad_atividade("29417", "FABRICAÇÃO DE PEÇAS E ACESSÓRIOS PARA O"));
		listaAtividadeEconomica.add(new Cad_atividade("29425", "FABRICAÇÃO DE PEÇAS E ACESSÓRIOS PARA OS"));
		listaAtividadeEconomica.add(new Cad_atividade("29433", "FABRICAÇÃO DE PEÇAS E ACESSÓRIOS PARA O"));
		listaAtividadeEconomica.add(new Cad_atividade("29441", "FABRICAÇÃO DE PEÇAS E ACESSÓRIOS PARA O"));
		listaAtividadeEconomica.add(new Cad_atividade("29450", "FABRICAÇÃO DE MATERIAL ELÉTRICO E ELETRÔ"));
		listaAtividadeEconomica.add(new Cad_atividade("29506", "RECONDICIONAMENTO E RECUPERAÇÃO DE MOTOR"));
		listaAtividadeEconomica.add(new Cad_atividade("30113", "CONSTRUÇÃO DE EMBARCAÇÕES E ESTRUTURAS F"));
		listaAtividadeEconomica.add(new Cad_atividade("30121", "CONSTRUÇÃO DE EMBARCAÇÕES PARA ESPORTE E"));
		listaAtividadeEconomica.add(new Cad_atividade("30318", "FABRICAÇÃO DE LOCOMOTIVAS, VAGÕES E OUTR"));
		listaAtividadeEconomica.add(new Cad_atividade("30326", "FABRICAÇÃO DE PEÇAS E ACESSÓRIOS PARA VE"));
		listaAtividadeEconomica.add(new Cad_atividade("30415", "FABRICAÇÃO DE AERONAVES"));
		listaAtividadeEconomica.add(new Cad_atividade("30423", "FABRICAÇÃO DE TURBINAS, MOTORES E OUTROS"));
		listaAtividadeEconomica.add(new Cad_atividade("30504", "FABRICAÇÃO DE VEÍCULOS MILITARES DE COMB"));
		listaAtividadeEconomica.add(new Cad_atividade("30911", "FABRICAÇÃO DE MOTOCICLETAS"));
		listaAtividadeEconomica.add(new Cad_atividade("30997", "FABRICAÇÃO DE EQUIPAMENTOS DE TRANSPORTE"));
		listaAtividadeEconomica.add(new Cad_atividade("31021", "FABRICAÇÃO DE MÓVEIS COM PREDOMINÂNCIA D"));
		listaAtividadeEconomica.add(new Cad_atividade("31047", "FABRICAÇÃO DE COLCHÕES"));
		listaAtividadeEconomica.add(new Cad_atividade("32116", "LAPIDAÇÃO DE GEMAS E FABRICAÇÃO DE ARTEF"));
		listaAtividadeEconomica.add(new Cad_atividade("32124", "FABRICAÇÃO DE BIJUTERIAS E ARTEFATOS SEM"));
		listaAtividadeEconomica.add(new Cad_atividade("32205", "FABRICAÇÃO DE INSTRUMENTOS MUSICAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("32302", "FABRICAÇÃO DE ARTEFATOS PARA PESCA E ESP"));
		listaAtividadeEconomica.add(new Cad_atividade("32914", "FABRICAÇÃO DE ESCOVAS, PINCÉIS E VASSOUR"));
		listaAtividadeEconomica.add(new Cad_atividade("32922", "FABRICAÇÃO DE EQUIPAMENTOS E ACESSÓRIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("33112", "MANUTENÇÃO E REPARAÇÃO DE TANQUES, RESER"));
		listaAtividadeEconomica.add(new Cad_atividade("33121", "MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E"));
		listaAtividadeEconomica.add(new Cad_atividade("33139", "MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQU"));
		listaAtividadeEconomica.add(new Cad_atividade("33147", "MANUTENÇÃO E REPARAÇÃO DE MÁQUINAS E EQU"));
		listaAtividadeEconomica.add(new Cad_atividade("33155", "MANUTENÇÃO E REPARAÇÃO DE VEÍCULOS FERRO"));
		listaAtividadeEconomica.add(new Cad_atividade("33163", "MANUTENÇÃO E REPARAÇÃO DE AERONAVES"));
		listaAtividadeEconomica.add(new Cad_atividade("33171", "MANUTENÇÃO E REPARAÇÃO DE EMBARCAÇÕES"));
		listaAtividadeEconomica.add(new Cad_atividade("33198", "MANUTENÇÃO E REPARAÇÃO DE EQUIPAMENTOS E"));
		listaAtividadeEconomica.add(new Cad_atividade("33210", "INSTALAÇÃO DE MÁQUINAS E EQUIPAMENTOS IN"));
		listaAtividadeEconomica.add(new Cad_atividade("33295", "INSTALAÇÃO DE EQUIPAMENTOS NÃO ESPECIFIC"));
		listaAtividadeEconomica.add(new Cad_atividade("35115", "GERAÇÃO DE ENERGIA ELÉTRICA"));
		listaAtividadeEconomica.add(new Cad_atividade("35123", "TRANSMISSÃO DE ENERGIA ELÉTRICA"));
		listaAtividadeEconomica.add(new Cad_atividade("35131", "COMÉRCIO ATACADISTA DE ENERGIA ELÉTRICA"));
		listaAtividadeEconomica.add(new Cad_atividade("35140", "DISTRIBUIÇÃO DE ENERGIA ELÉTRICA"));
		listaAtividadeEconomica.add(new Cad_atividade("35204", "PRODUÇÃO DE GÁS; PROCESSAMENTO DE GÁS NA"));
		listaAtividadeEconomica.add(new Cad_atividade("35301", "PRODUÇÃO E DISTRIBUIÇÃO DE VAPOR, ÁGUA Q"));
		listaAtividadeEconomica.add(new Cad_atividade("37011", "GESTÃO DE REDES DE ESGOTO"));
		listaAtividadeEconomica.add(new Cad_atividade("37029", "ATIVIDADES RELACIONADAS A ESGOTO, EXCETO"));
		listaAtividadeEconomica.add(new Cad_atividade("38114", "COLETA DE RESÍDUOS NÃO-PERIGOSOS"));
		listaAtividadeEconomica.add(new Cad_atividade("38122", "COLETA DE RESÍDUOS PERIGOSOS"));
		listaAtividadeEconomica.add(new Cad_atividade("38211", "TRATAMENTO E DISPOSIÇÃO DE RESÍDUOS NÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("38220", "TRATAMENTO E DISPOSIÇÃO DE RESÍDUOS PERI"));
		listaAtividadeEconomica.add(new Cad_atividade("38319", "RECUPERAÇÃO DE MATERIAIS METÁLICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("38327", "RECUPERAÇÃO DE MATERIAIS PLÁSTICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("38394", "RECUPERAÇÃO DE MATERIAIS NÃO ESPECIFICAD"));
		listaAtividadeEconomica.add(new Cad_atividade("39005", "DESCONTAMINAÇÃO E OUTROS SERVIÇOS DE GES"));
		listaAtividadeEconomica.add(new Cad_atividade("41204", "CONSTRUÇÃO DE EDIFÍCIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("42111", "CONSTRUÇÃO DE RODOVIAS E FERROVIAS"));
		listaAtividadeEconomica.add(new Cad_atividade("42120", "CONSTRUÇÃO DE OBRASDEARTE ESPECIAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("42138", "OBRAS DE URBANIZAÇÃO - RUAS, PRAÇAS E CA"));
		listaAtividadeEconomica.add(new Cad_atividade("42227", "CONSTRUÇÃO DE REDES DE ABASTECIMENTO DE"));
		listaAtividadeEconomica.add(new Cad_atividade("42235", "CONSTRUÇÃO DE REDES DE TRANSPORTES POR D"));
		listaAtividadeEconomica.add(new Cad_atividade("42910", "OBRAS PORTUÁRIAS, MARÍTIMAS E FLUVIAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("42995", "OBRAS DE ENGENHARIA CIVIL NÃO ESPECIFICA"));
		listaAtividadeEconomica.add(new Cad_atividade("43118", "DEMOLIÇÃO E PREPARAÇÃO DE CANTEIROS DE O"));
		listaAtividadeEconomica.add(new Cad_atividade("43126", "PERFURAÇÕES E SONDAGENS"));
		listaAtividadeEconomica.add(new Cad_atividade("43134", "OBRAS DE TERRAPLENAGEM"));
		listaAtividadeEconomica.add(new Cad_atividade("43193", "SERVIÇOS DE PREPARAÇÃO DO TERRENO NÃO ES"));
		listaAtividadeEconomica.add(new Cad_atividade("43215", "INSTALAÇÕES ELÉTRICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("43223", "INSTALAÇÕES HIDRÁULICAS, DE SISTEMAS DE"));
		listaAtividadeEconomica.add(new Cad_atividade("43304", "OBRAS DE ACABAMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("43916", "OBRAS DE FUNDAÇÕES"));
		listaAtividadeEconomica.add(new Cad_atividade("43991", "SERVIÇOS ESPECIALIZADOS PARA CONSTRUÇÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("45129", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("45421", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("45439", "MANUTENÇÃO E REPARAÇÃO DE MOTOCICLETAS"));
		listaAtividadeEconomica.add(new Cad_atividade("46117", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46125", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46133", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46141", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46150", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46168", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46176", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46184", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46192", "REPRESENTANTES COMERCIAIS E AGENTES DO C"));
		listaAtividadeEconomica.add(new Cad_atividade("46214", "COMÉRCIO ATACADISTA DE CAFÉ EM GRÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("46222", "COMÉRCIO ATACADISTA DE SOJA"));
		listaAtividadeEconomica.add(new Cad_atividade("46231", "COMÉRCIO ATACADISTA DE ANIMAIS VIVOS, AL"));
		listaAtividadeEconomica.add(new Cad_atividade("46311", "COMÉRCIO ATACADISTA DE LEITE E LATICÍNIO"));
		listaAtividadeEconomica.add(new Cad_atividade("46320", "COMÉRCIO ATACADISTA DE CEREAIS E LEGUMIN"));
		listaAtividadeEconomica.add(new Cad_atividade("46354", "COMÉRCIO ATACADISTA DE BEBIDAS"));
		listaAtividadeEconomica.add(new Cad_atividade("46362", "COMÉRCIO ATACADISTA DE PRODUTOS DO FUMO"));
		listaAtividadeEconomica.add(new Cad_atividade("46371", "COMÉRCIO ATACADISTA ESPECIALIZADO EM PRO"));
		listaAtividadeEconomica.add(new Cad_atividade("46419", "COMÉRCIO ATACADISTA DE TECIDOS, ARTEFATO"));
		listaAtividadeEconomica.add(new Cad_atividade("46451", "COMÉRCIO ATACADISTA DE INSTRUMENTOS E MA"));
		listaAtividadeEconomica.add(new Cad_atividade("46494", "COMÉRCIO ATACADISTA DE EQUIPAMENTOS E AR"));
		listaAtividadeEconomica.add(new Cad_atividade("46516", "COMÉRCIO ATACADISTA DE COMPUTADORES, PER"));
		listaAtividadeEconomica.add(new Cad_atividade("46621", "COMÉRCIO ATACADISTA DE MÁQUINAS, EQUIPAM"));
		listaAtividadeEconomica.add(new Cad_atividade("46630", "COMÉRCIO ATACADISTA DE MÁQUINAS E EQUIPA"));
		listaAtividadeEconomica.add(new Cad_atividade("46648", "COMÉRCIO ATACADISTA DE MÁQUINAS, APARELH"));
		listaAtividadeEconomica.add(new Cad_atividade("46729", "COMÉRCIO ATACADISTA DE FERRAGENS E FERRA"));
		listaAtividadeEconomica.add(new Cad_atividade("46737", "COMÉRCIO ATACADISTA DE MATERIAL ELÉTRICO"));
		listaAtividadeEconomica.add(new Cad_atividade("46745", "COMÉRCIO ATACADISTA DE CIMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("46796", "COMÉRCIO ATACADISTA ESPECIALIZADO DE MAT"));
		listaAtividadeEconomica.add(new Cad_atividade("46826", "COMÉRCIO ATACADISTA DE GÁS LIQÜEFEITO DE"));
		listaAtividadeEconomica.add(new Cad_atividade("46851", "COMÉRCIO ATACADISTA DE PRODUTOS SIDERÚRG"));
		listaAtividadeEconomica.add(new Cad_atividade("46869", "COMÉRCIO ATACADISTA DE PAPEL E PAPELÃO E"));
		listaAtividadeEconomica.add(new Cad_atividade("46915", "COMÉRCIO ATACADISTA DE MERCADORIAS EM GE"));
		listaAtividadeEconomica.add(new Cad_atividade("46931", "COM ATAC DE MERCAD EM GERAL S/PRED ALIM"));
		listaAtividadeEconomica.add(new Cad_atividade("47130", "COMÉRCIO VAREJISTA DE MERCADORIAS EM GER"));
		listaAtividadeEconomica.add(new Cad_atividade("47229", "COMÉRCIO VAREJISTA DE CARNES E PESCADOS"));
		listaAtividadeEconomica.add(new Cad_atividade("47237", "COMÉRCIO VAREJISTA DE BEBIDAS"));
		listaAtividadeEconomica.add(new Cad_atividade("47245", "COMÉRCIO VAREJISTA DE HORTIFRUTIGRANJEIR"));
		listaAtividadeEconomica.add(new Cad_atividade("47318", "COMÉRCIO VAREJISTA DE COMBUSTÍVEIS PARA"));
		listaAtividadeEconomica.add(new Cad_atividade("47326", "COMÉRCIO VAREJISTA DE LUBRIFICANTES"));
		listaAtividadeEconomica.add(new Cad_atividade("47415", "COMÉRCIO VAREJISTA DE TINTAS E MATERIAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("47423", "COMÉRCIO VAREJISTA DE MATERIAL ELÉTRICO"));
		listaAtividadeEconomica.add(new Cad_atividade("47431", "COMÉRCIO VAREJISTA DE VIDROS"));
		listaAtividadeEconomica.add(new Cad_atividade("47512", "COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUI"));
		listaAtividadeEconomica.add(new Cad_atividade("47521", "COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUI"));
		listaAtividadeEconomica.add(new Cad_atividade("47539", "COMÉRCIO VAREJISTA ESPECIALIZADO DE ELET"));
		listaAtividadeEconomica.add(new Cad_atividade("47563", "COMÉRCIO VAREJISTA ESPECIALIZADO DE INST"));
		listaAtividadeEconomica.add(new Cad_atividade("47571", "COMÉRCIO VAREJISTA ESPECIALIZADO DE PEÇA"));
		listaAtividadeEconomica.add(new Cad_atividade("47598", "COMÉRCIO VAREJISTA DE ARTIGOS DE USO DOM"));
		listaAtividadeEconomica.add(new Cad_atividade("47628", "COMÉRCIO VAREJISTA DE DISCOS, CDS, DVDS"));
		listaAtividadeEconomica.add(new Cad_atividade("47636", "COMÉRCIO VAREJISTA DE ARTIGOS RECREATIVO"));
		listaAtividadeEconomica.add(new Cad_atividade("47717", "COMÉRCIO VAREJISTA DE PRODUTOS FARMACÊUT"));
		listaAtividadeEconomica.add(new Cad_atividade("47725", "COMÉRCIO VAREJISTA DE COSMÉTICOS, PRODUT"));
		listaAtividadeEconomica.add(new Cad_atividade("47733", "COMÉRCIO VAREJISTA DE ARTIGOS MÉDICOS E"));
		listaAtividadeEconomica.add(new Cad_atividade("47741", "COMÉRCIO VAREJISTA DE ARTIGOS DE ÓPTICA"));
		listaAtividadeEconomica.add(new Cad_atividade("47822", "COMÉRCIO VAREJISTA DE CALÇADOS E ARTIGOS"));
		listaAtividadeEconomica.add(new Cad_atividade("47831", "COMÉRCIO VAREJISTA DE JÓIAS E RELÓGIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("47857", "COMÉRCIO VAREJISTA DE ARTIGOS USADOS"));
		listaAtividadeEconomica.add(new Cad_atividade("47903", "COMÉRCIO AMBULANTE E OUTROS TIPOS DE COM"));
		listaAtividadeEconomica.add(new Cad_atividade("49116", "TRANSPORTE FERROVIÁRIO DE CARGA"));
		listaAtividadeEconomica.add(new Cad_atividade("49124", "TRANSPORTE METROFERROVIÁRIO DE PASSAGEIR"));
		listaAtividadeEconomica.add(new Cad_atividade("49213", "TRANSPORTE RODOVIÁRIO COLETIVO DE PASSAG"));
		listaAtividadeEconomica.add(new Cad_atividade("49230", "TRANSPORTE RODOVIÁRIO DE TÁXI"));
		listaAtividadeEconomica.add(new Cad_atividade("49248", "TRANSPORTE ESCOLAR"));
		listaAtividadeEconomica.add(new Cad_atividade("49299", "TRANSPORTE RODOVIÁRIO COLETIVO DE PASSAG"));
		listaAtividadeEconomica.add(new Cad_atividade("49302", "TRANSPORTE RODOVIARIO DE CARGA"));
		listaAtividadeEconomica.add(new Cad_atividade("49400", "TRANSPORTE DUTOVIÁRIO"));
		listaAtividadeEconomica.add(new Cad_atividade("49507", "TRENS TURÍSTICOS, TELEFÉRICOS E SIMILARE"));
		listaAtividadeEconomica.add(new Cad_atividade("50114", "TRANSPORTE MARÍTIMO DE CABOTAGEM"));
		listaAtividadeEconomica.add(new Cad_atividade("50122", "TRANSPORTE MARÍTIMO DE LONGO CURSO"));
		listaAtividadeEconomica.add(new Cad_atividade("50211", "TRANSPORTE POR NAVEGAÇÃO INTERIOR DE CAR"));
		listaAtividadeEconomica.add(new Cad_atividade("50220", "TRANSPORTE POR NAVEGAÇÃO INTERIOR DE PAS"));
		listaAtividadeEconomica.add(new Cad_atividade("50301", "NAVEGAÇÃO DE APOIO"));
		listaAtividadeEconomica.add(new Cad_atividade("50912", "TRANSPORTE POR NAVEGAÇÃO DE TRAVESSIA"));
		listaAtividadeEconomica.add(new Cad_atividade("51111", "TRANSPORTE AÉREO DE PASSAGEIROS REGULAR"));
		listaAtividadeEconomica.add(new Cad_atividade("51129", "TRANSPORTE AÉREO DE PASSAGEIROS NÃO-REGU"));
		listaAtividadeEconomica.add(new Cad_atividade("51200", "TRANSPORTE AÉREO DE CARGA"));
		listaAtividadeEconomica.add(new Cad_atividade("51307", "TRANSPORTE ESPACIAL"));
		listaAtividadeEconomica.add(new Cad_atividade("52117", "ARMAZENAMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("52125", "CARGA E DESCARGA"));
		listaAtividadeEconomica.add(new Cad_atividade("52159", "COMÉRCIO VAREJISTA NÃO ESPECIALIZADO, SE"));
		listaAtividadeEconomica.add(new Cad_atividade("52214", "CONCESSIONÁRIAS DE RODOVIAS, PONTES, TÚN"));
		listaAtividadeEconomica.add(new Cad_atividade("52222", "TERMINAIS RODOVIÁRIOS E FERROVIÁRIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("52231", "ESTACIONAMENTO DE VEÍCULOS"));
		listaAtividadeEconomica.add(new Cad_atividade("52311", "GESTÃO DE PORTOS E TERMINAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("52320", "ATIVIDADES DE AGENCIAMENTO MARÍTIMO"));
		listaAtividadeEconomica.add(new Cad_atividade("52397", "ATIVIDADES AUXILIARES DOS TRANSPORTES AQ"));
		listaAtividadeEconomica.add(new Cad_atividade("53105", "ATIVIDADES DE CORREIO"));
		listaAtividadeEconomica.add(new Cad_atividade("53202", "ATIVIDADES DE MALOTE E DE ENTREGA"));
		listaAtividadeEconomica.add(new Cad_atividade("55108", "HOTÉIS E SIMILARES"));
		listaAtividadeEconomica.add(new Cad_atividade("56121", "SERVIÇOS AMBULANTES DE ALIMENTAÇÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("58115", "EDIÇÃO DE LIVROS"));
		listaAtividadeEconomica.add(new Cad_atividade("58123", "EDIÇÃO DE JORNAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("58131", "EDIÇÃO DE REVISTAS"));
		listaAtividadeEconomica.add(new Cad_atividade("58191", "EDIÇÃO DE CADASTROS, LISTAS E OUTROS PRO"));
		listaAtividadeEconomica.add(new Cad_atividade("58212", "EDIÇÃO INTEGRADA À IMPRESSÃO DE LIVROS"));
		listaAtividadeEconomica.add(new Cad_atividade("58221", "EDIÇÃO INTEGRADA À IMPRESSÃO DE JORNAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("58239", "EDIÇÃO INTEGRADA À IMPRESSÃO DE REVISTAS"));
		listaAtividadeEconomica.add(new Cad_atividade("59111", "ATIVIDADES DE PRODUÇÃO CINEMATOGRÁFICA,"));
		listaAtividadeEconomica.add(new Cad_atividade("59120", "ATIVIDADES DE PÓS-PRODUÇÃO CINEMATOGRÁFI"));
		listaAtividadeEconomica.add(new Cad_atividade("59138", "DISTRIBUIÇÃO CINEMATOGRÁFICA, DE VÍDEO E"));
		listaAtividadeEconomica.add(new Cad_atividade("59146", "ATIVIDADES DE EXIBIÇÃO CINEMATOGRÁFICA"));
		listaAtividadeEconomica.add(new Cad_atividade("59201", "ATIVIDADES DE GRAVAÇÃO DE SOM E DE EDIÇÃ"));
		listaAtividadeEconomica.add(new Cad_atividade("60101", "ATIVIDADES DE RÁDIO"));
		listaAtividadeEconomica.add(new Cad_atividade("60217", "ATIVIDADES DE TELEVISÃO ABERTA"));
		listaAtividadeEconomica.add(new Cad_atividade("60225", "PROGRAMADORAS E ATIVIDADES RELACIONADAS"));
		listaAtividadeEconomica.add(new Cad_atividade("61108", "TELECOMUNICAÇÕES POR FIO"));
		listaAtividadeEconomica.add(new Cad_atividade("61205", "TELECOMUNICAÇÕES SEM FIO"));
		listaAtividadeEconomica.add(new Cad_atividade("61302", "TELECOMUNICAÇÕES POR SATÉLITE"));
		listaAtividadeEconomica.add(new Cad_atividade("61418", "OPERADORAS DE TELEVISÃO POR ASSINATURA P"));
		listaAtividadeEconomica.add(new Cad_atividade("61426", "OPERADORAS DE TELEVISÃO POR ASSINATURA P"));
		listaAtividadeEconomica.add(new Cad_atividade("61434", "OPERADORAS DE TELEVISÃO POR ASSINATURA P"));
		listaAtividadeEconomica.add(new Cad_atividade("61906", "OUTRAS ATIVIDADES DE TELECOMUNICAÇÕES"));
		listaAtividadeEconomica.add(new Cad_atividade("62015", "DESENVOLVIMENTO DE PROGRAMAS DE COMPUTAD"));
		listaAtividadeEconomica.add(new Cad_atividade("62023", "DESENVOLVIMENTO E LICENCIAMENTO DE PROGR"));
		listaAtividadeEconomica.add(new Cad_atividade("62031", "DESENVOLVIMENTO E LICENCIAMENTO DE PROGR"));
		listaAtividadeEconomica.add(new Cad_atividade("62040", "CONSULTORIA EM TECNOLOGIA DA INFORMAÇÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("62091", "SUPORTE TÉCNICO, MANUTENÇÃO E OUTROS SER"));
		listaAtividadeEconomica.add(new Cad_atividade("63194", "PORTAIS, PROVEDORES DE CONTEÚDO E OUTROS"));
		listaAtividadeEconomica.add(new Cad_atividade("63917", "AGÊNCIAS DE NOTÍCIAS"));
		listaAtividadeEconomica.add(new Cad_atividade("64107", "BANCO CENTRAL"));
		listaAtividadeEconomica.add(new Cad_atividade("64212", "BANCOS COMERCIAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("64221", "BANCOS MÚLTIPLOS, COM CARTEIRA COMERCIAL"));
		listaAtividadeEconomica.add(new Cad_atividade("64239", "CAIXAS ECONÔMICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("64247", "CRÉDITO COOPERATIVO"));
		listaAtividadeEconomica.add(new Cad_atividade("64310", "BANCOS MÚLTIPLOS, SEM CARTEIRA COMERCIAL"));
		listaAtividadeEconomica.add(new Cad_atividade("64328", "BANCOS DE INVESTIMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("64336", "BANCOS DE DESENVOLVIMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("64344", "AGÊNCIAS DE FOMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("64352", "CRÉDITO IMOBILIÁRIO"));
		listaAtividadeEconomica.add(new Cad_atividade("64361", "SOCIEDADES DE CRÉDITO, FINANCIAMENTO E I"));
		listaAtividadeEconomica.add(new Cad_atividade("64379", "SOCIEDADES DE CRÉDITO AO MICROEMPREENDED"));
		listaAtividadeEconomica.add(new Cad_atividade("64409", "ARRENDAMENTO MERCANTIL"));
		listaAtividadeEconomica.add(new Cad_atividade("64506", "SOCIEDADES DE CAPITALIZAÇÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("64611", "HOLDINGS DE INSTITUIÇÕES FINANCEIRAS"));
		listaAtividadeEconomica.add(new Cad_atividade("64620", "HOLDINGS DE INSTITUIÇÕES NÃO-FINANCEIRAS"));
		listaAtividadeEconomica.add(new Cad_atividade("64638", "OUTRAS SOCIEDADES DE PARTICIPAÇÃO, EXCET"));
		listaAtividadeEconomica.add(new Cad_atividade("64701", "FUNDOS DE INVESTIMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("64913", "SOCIEDADES DE FOMENTO MERCANTIL - FACTOR"));
		listaAtividadeEconomica.add(new Cad_atividade("64921", "SECURITIZAÇÃO DE CRÉDITOS"));
		listaAtividadeEconomica.add(new Cad_atividade("64930", "ADMINISTRAÇÃO DE CONSÓRCIOS PARA AQUISIÇ"));
		listaAtividadeEconomica.add(new Cad_atividade("64999", "OUTRAS ATIVIDADES DE SERVIÇOS FINANCEIRO"));
		listaAtividadeEconomica.add(new Cad_atividade("65111", "SEGUROS DE VIDA"));
		listaAtividadeEconomica.add(new Cad_atividade("65120", "SEGUROS NÃO-VIDA"));
		listaAtividadeEconomica.add(new Cad_atividade("65201", "SEGUROS-SAÚDE"));
		listaAtividadeEconomica.add(new Cad_atividade("65308", "RESSEGUROS"));
		listaAtividadeEconomica.add(new Cad_atividade("65413", "PREVIDÊNCIA COMPLEMENTAR FECHADA"));
		listaAtividadeEconomica.add(new Cad_atividade("65421", "PREVIDÊNCIA COMPLEMENTAR ABERTA"));
		listaAtividadeEconomica.add(new Cad_atividade("65502", "PLANOS DE SAÚDE"));
		listaAtividadeEconomica.add(new Cad_atividade("66118", "ADMINISTRAÇÃO DE BOLSAS E MERCADOS DE BA"));
		listaAtividadeEconomica.add(new Cad_atividade("66126", "ATIVIDADES DE INTERMEDIÁRIOS EM TRANSAÇÕ"));
		listaAtividadeEconomica.add(new Cad_atividade("66134", "ADMINISTRAÇÃO DE CARTÕES DE CRÉDITO"));
		listaAtividadeEconomica.add(new Cad_atividade("66215", "AVALIAÇÃO DE RISCOS E PERDAS"));
		listaAtividadeEconomica.add(new Cad_atividade("66223", "CORRETORES E AGENTES DE SEGUROS, DE PLAN"));
		listaAtividadeEconomica.add(new Cad_atividade("66291", "ATIVIDADES AUXILIARES DOS SEGUROS, DA PR"));
		listaAtividadeEconomica.add(new Cad_atividade("66304", "ATIVIDADES DE ADMINISTRAÇÃO DE FUNDOS PO"));
		listaAtividadeEconomica.add(new Cad_atividade("68226", "GESTÃO E ADMINISTRAÇÃO DA PROPRIEDADE IM"));
		listaAtividadeEconomica.add(new Cad_atividade("69117", "ATIVIDADES JURÍDICAS, EXCETO CARTÓRIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("69125", "CARTÓRIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("70204", "ATIVIDADES DE CONSULTORIA EM GESTÃO EMPR"));
		listaAtividadeEconomica.add(new Cad_atividade("71111", "SERVIÇOS DE ARQUITETURA"));
		listaAtividadeEconomica.add(new Cad_atividade("71120", "SERVIÇOS DE ENGENHARIA"));
		listaAtividadeEconomica.add(new Cad_atividade("71197", "ATIVIDADES TÉCNICAS RELACIONADAS À ARQUI"));
		listaAtividadeEconomica.add(new Cad_atividade("71201", "PESQUISA E DESENVOLVIMENTO EXPERIMENTAL"));
		listaAtividadeEconomica.add(new Cad_atividade("72100", "PESQUISA E DESENVOLVIMENTO EXPERIMENTAL"));
		listaAtividadeEconomica.add(new Cad_atividade("72207", "PESQUISA E DESENVOLVIMENTO EXPERIMENTAL"));
		listaAtividadeEconomica.add(new Cad_atividade("73114", "AGÊNCIAS DE PUBLICIDADE"));
		listaAtividadeEconomica.add(new Cad_atividade("73122", "AGENCIAMENTO DE ESPAÇOS PARA PUBLICIDADE"));
		listaAtividadeEconomica.add(new Cad_atividade("73190", "ATIVIDADES DE PUBLICIDADE NÃO ESPECIFICA"));
		listaAtividadeEconomica.add(new Cad_atividade("73203", "PESQUISAS DE MERCADO E DE OPINIÃO PÚBLIC"));
		listaAtividadeEconomica.add(new Cad_atividade("74102", "DESIGN E DECORAÇÃO DE INTERIORES"));
		listaAtividadeEconomica.add(new Cad_atividade("74200", "ATIVIDADES FOTOGRÁFICAS E SIMILARES"));
		listaAtividadeEconomica.add(new Cad_atividade("74901", "ATIVIDADES PROFISSIONAIS, CIENTÍFICAS E"));
		listaAtividadeEconomica.add(new Cad_atividade("75001", "ATIVIDADES VETERINÁRIAS"));
		listaAtividadeEconomica.add(new Cad_atividade("77110", "LOCAÇÃO DE AUTOMÓVEIS SEM CONDUTOR"));
		listaAtividadeEconomica.add(new Cad_atividade("77195", "LOCAÇÃO DE MEIOS DE TRANSPORTE, EXCETO A"));
		listaAtividadeEconomica.add(new Cad_atividade("77217", "ALUGUEL DE EQUIPAMENTOS RECREATIVOS E ES"));
		listaAtividadeEconomica.add(new Cad_atividade("77225", "ALUGUEL DE FITAS DE VÍDEO, DVDS E SIMILA"));
		listaAtividadeEconomica.add(new Cad_atividade("77233", "ALUGUEL DE OBJETOS DO VESTUÁRIO, JÓIAS E"));
		listaAtividadeEconomica.add(new Cad_atividade("77292", "ALUGUEL DE OBJETOS PESSOAIS E DOMÉSTICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("77314", "ALUGUEL DE MÁQUINAS E EQUIPAMENTOS AGRÍC"));
		listaAtividadeEconomica.add(new Cad_atividade("77322", "ALUGUEL DE MÁQUINAS E EQUIPAMENTOS PARA"));
		listaAtividadeEconomica.add(new Cad_atividade("77331", "ALUGUEL DE MÁQUINAS E EQUIPAMENTOS PARA"));
		listaAtividadeEconomica.add(new Cad_atividade("77403", "GESTÃO DE ATIVOS INTANGÍVEIS NÃO-FINANCE"));
		listaAtividadeEconomica.add(new Cad_atividade("78108", "SELEÇÃO E AGENCIAMENTO DE MÃO-DE-OBRA"));
		listaAtividadeEconomica.add(new Cad_atividade("78205", "LOCAÇÃO DE MÃO-DE-OBRA TEMPORÁRIA"));
		listaAtividadeEconomica.add(new Cad_atividade("78302", "FORNECIMENTO E GESTÃO DE RECURSOS HUMANO"));
		listaAtividadeEconomica.add(new Cad_atividade("79112", "AGÊNCIAS DE VIAGENS"));
		listaAtividadeEconomica.add(new Cad_atividade("79121", "OPERADORES TURÍSTICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("79902", "SERVIÇOS DE RESERVAS E OUTROS SERVIÇOS D"));
		listaAtividadeEconomica.add(new Cad_atividade("80111", "ATIVIDADES DE VIGILÂNCIA E SEGURANÇA PRI"));
		listaAtividadeEconomica.add(new Cad_atividade("80129", "ATIVIDADES DE TRANSPORTE DE VALORES"));
		listaAtividadeEconomica.add(new Cad_atividade("80200", "ATIVIDADES DE MONITORAMENTO DE SISTEMAS"));
		listaAtividadeEconomica.add(new Cad_atividade("80307", "ATIVIDADES DE INVESTIGAÇÃO PARTICULAR"));
		listaAtividadeEconomica.add(new Cad_atividade("81117", "SERVIÇOS COMBINADOS PARA APOIO A EDIFÍCI"));
		listaAtividadeEconomica.add(new Cad_atividade("81125", "CONDOMINIOS PREDIAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("81214", "LIMPEZA EM PRÉDIOS E EM DOMICÍLIOS"));
		listaAtividadeEconomica.add(new Cad_atividade("81222", "IMUNIZAÇÃO E CONTROLE DE PRAGAS URBANAS"));
		listaAtividadeEconomica.add(new Cad_atividade("81290", "ATIVIDADES DE LIMPEZA NÃO ESPECIFICADAS"));
		listaAtividadeEconomica.add(new Cad_atividade("81303", "ATIVIDADES PAISAGÍSTICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("82113", "SERVIÇOS COMBINADOS DE ESCRITÓRIO E APOI"));
		listaAtividadeEconomica.add(new Cad_atividade("82199", "FOTOCÓPIAS, PREPARAÇÃO DE DOCUMENTOS E O"));
		listaAtividadeEconomica.add(new Cad_atividade("82202", "ATIVIDADES DE TELEATENDIMENTO"));
		listaAtividadeEconomica.add(new Cad_atividade("82300", "ATIVIDADES DE ORGANIZAÇÃO DE EVENTOS, EX"));
		listaAtividadeEconomica.add(new Cad_atividade("82911", "ATIVIDADES DE COBRANÇA E INFORMAÇÕES CAD"));
		listaAtividadeEconomica.add(new Cad_atividade("82920", "ENVASAMENTO E EMPACOTAMENTO SOB CONTRATO"));
		listaAtividadeEconomica.add(new Cad_atividade("82997", "ATIVIDADES DE SERVIÇOS PRESTADOS PRINCIP"));
		listaAtividadeEconomica.add(new Cad_atividade("84116", "ADMINISTRAÇÃO PUBLICA EM GERAL"));
		listaAtividadeEconomica.add(new Cad_atividade("84124", "REGULAÇÃO DAS ATIVIDADES DE SAÚDE, EDUCA"));
		listaAtividadeEconomica.add(new Cad_atividade("84132", "REGULAÇÃO DAS ATIVIDADES ECONÔMICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("84213", "RELAÇÕES EXTERIORES"));
		listaAtividadeEconomica.add(new Cad_atividade("84221", "DEFESA"));
		listaAtividadeEconomica.add(new Cad_atividade("84230", "JUSTIÇA"));
		listaAtividadeEconomica.add(new Cad_atividade("84248", "SEGURANÇA E ORDEM PÚBLICA"));
		listaAtividadeEconomica.add(new Cad_atividade("84256", "DEFESA CIVIL"));
		listaAtividadeEconomica.add(new Cad_atividade("84302", "SEGURIDADE SOCIAL OBRIGATÓRIA"));
		listaAtividadeEconomica.add(new Cad_atividade("85112", "EDUCAÇÃO INFANTIL - CRECHE"));
		listaAtividadeEconomica.add(new Cad_atividade("85121", "EDUCAÇÃO INFANTIL  PRÉESCOLA"));
		listaAtividadeEconomica.add(new Cad_atividade("85139", "ENSINO FUNDAMENTAL"));
		listaAtividadeEconomica.add(new Cad_atividade("85201", "ENSINO MÉDIO"));
		listaAtividadeEconomica.add(new Cad_atividade("85317", "EDUCAÇÃO SUPERIOR  GRADUAÇÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("85325", "EDUCAÇÃO SUPERIOR - GRADUAÇÃO E PÓS-GRAD"));
		listaAtividadeEconomica.add(new Cad_atividade("85333", "EDUCAÇÃO SUPERIOR - PÓS-GRADUAÇÃO E EXTE"));
		listaAtividadeEconomica.add(new Cad_atividade("85414", "EDUCAÇÃO PROFISSIONAL DE NÍVEL TÉCNICO"));
		listaAtividadeEconomica.add(new Cad_atividade("85422", "EDUCAÇÃO PROFISSIONAL DE NÍVEL TECNOLÓGI"));
		listaAtividadeEconomica.add(new Cad_atividade("85503", "ATIVIDADES DE APOIO À EDUCAÇÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("85911", "ENSINO DE ESPORTES"));
		listaAtividadeEconomica.add(new Cad_atividade("85929", "ENSINO DE ARTE E CULTURA"));
		listaAtividadeEconomica.add(new Cad_atividade("85937", "ENSINO DE IDIOMAS"));
		listaAtividadeEconomica.add(new Cad_atividade("85996", "ATIVIDADES DE ENSINO NÃO ESPECIFICADAS A"));
		listaAtividadeEconomica.add(new Cad_atividade("86101", "ATIVIDADES DE ATENDIMENTO HOSPITALAR"));
		listaAtividadeEconomica.add(new Cad_atividade("86216", "SERVIÇOS MÓVEIS DE ATENDIMENTO A URGÊNCI"));
		listaAtividadeEconomica.add(new Cad_atividade("86224", "SERVIÇOS DE REMOÇÃO DE PACIENTES, EXCETO"));
		listaAtividadeEconomica.add(new Cad_atividade("86305", "ATIVIDADES DE ATENÇÃO AMBULATORIAL EXECU"));
		listaAtividadeEconomica.add(new Cad_atividade("86607", "ATIVIDADES DE APOIO À GESTÃO DE SAÚDE"));
		listaAtividadeEconomica.add(new Cad_atividade("86909", "ATIVIDADES DE ATENÇÃO À SAÚDE HUMANA NÃO"));
		listaAtividadeEconomica.add(new Cad_atividade("87115", "ATIVIDADES DE ASSISTÊNCIA A IDOSOS, DEFI"));
		listaAtividadeEconomica.add(new Cad_atividade("87123", "ATIVIDADES DE FORNECIMENTO DE INFRA-ESTR"));
		listaAtividadeEconomica.add(new Cad_atividade("87204", "ATIVIDADES DE ASSISTÊNCIA PSICOSSOCIAL E"));
		listaAtividadeEconomica.add(new Cad_atividade("87301", "ATIVIDADES DE ASSISTÊNCIA SOCIAL PRESTAD"));
		listaAtividadeEconomica.add(new Cad_atividade("90019", "ARTES CÊNICAS, ESPETÁCULOS E ATIVIDADES"));
		listaAtividadeEconomica.add(new Cad_atividade("90027", "CRIAÇÃO ARTÍSTICA"));
		listaAtividadeEconomica.add(new Cad_atividade("91015", "ATIVIDADES DE BIBLIOTECAS E ARQUIVOS"));
		listaAtividadeEconomica.add(new Cad_atividade("91023", "ATIVIDADES DE MUSEUS E DE EXPLORAÇÃO, RE"));
		listaAtividadeEconomica.add(new Cad_atividade("91031", "ATIVIDADES DE JARDINS BOTÂNICOS, ZOOLÓGI"));
		listaAtividadeEconomica.add(new Cad_atividade("92003", "ATIVIDADES DE EXPLORAÇÃO DE JOGOS DE AZA"));
		listaAtividadeEconomica.add(new Cad_atividade("93115", "GESTÃO DE INSTALAÇÕES DE ESPORTES"));
		listaAtividadeEconomica.add(new Cad_atividade("93123", "CLUBES SOCIAIS, ESPORTIVOS E SIMILARES"));
		listaAtividadeEconomica.add(new Cad_atividade("93131", "ATIVIDADES DE CONDICIONAMENTO FÍSICO"));
		listaAtividadeEconomica.add(new Cad_atividade("93212", "PARQUES DE DIVERSÃO E PARQUES TEMÁTICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("93298", "ATIVIDADES DE RECREAÇÃO E LAZER NÃO ESPE"));
		listaAtividadeEconomica.add(new Cad_atividade("94111", "ATIVIDADES DE ORGANIZAÇÕES ASSOCIATIVAS"));
		listaAtividadeEconomica.add(new Cad_atividade("94201", "ATIVIDADES DE ORGANIZAÇÕES SINDICAIS"));
		listaAtividadeEconomica.add(new Cad_atividade("94308", "ATIVIDADES DE ASSOCIAÇÕES DE DEFESA DE D"));
		listaAtividadeEconomica.add(new Cad_atividade("94910", "ATIVIDADES DE ORGANIZAÇÕES RELIGIOSAS"));
		listaAtividadeEconomica.add(new Cad_atividade("94928", "ATIVIDADES DE ORGANIZAÇÕES POLÍTICAS"));
		listaAtividadeEconomica.add(new Cad_atividade("94936", "ATIVIDADES DE ORGANIZAÇÕES ASSOCIATIVAS"));
		listaAtividadeEconomica.add(new Cad_atividade("95118", "REPARAÇÃO E MANUTENÇÃO DE COMPUTADORES E"));
		listaAtividadeEconomica.add(new Cad_atividade("95126", "REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS D"));
		listaAtividadeEconomica.add(new Cad_atividade("95291", "REPARAÇÃO E MANUTENÇÃO DE OBJETOS E EQUI"));
		listaAtividadeEconomica.add(new Cad_atividade("96017", "LAVANDERIAS, TINTURARIAS E TOALHEIROS"));
		listaAtividadeEconomica.add(new Cad_atividade("97005", "SERVIÇOS DOMÉSTICOS"));
		listaAtividadeEconomica.add(new Cad_atividade("99008", "ORGANISMOS INTERNACIONAIS E OUTRAS INSTI"));
		listaAtividadeEconomica.add(new Cad_atividade("99999", "OUTRAS ATIVIDADES NÃO ESPECIFICADAS"));
		
		return listaAtividadeEconomica;
	}
	*/
	
	
}
